name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - master # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_EMAIL_JS_PUBLIC_KEY: ${{ secrets.VITE_EMAIL_JS_PUBLIC_KEY }}
      VITE_EMAIL_JS_SERVICE_ID: ${{ secrets.VITE_EMAIL_JS_SERVICE_ID }}
      VITE_EMAIL_JS_TEMPLATE_ID: ${{ secrets.VITE_EMAIL_JS_TEMPLATE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build the Vite app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
