name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - master # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "VITE_EMAIL_JS_PUBLIC_KEY=${{ secrets.VITE_EMAIL_JS_PUBLIC_KEY }}" >> .env
          echo "VITE_EMAIL_JS_SERVICE_ID=${{ secrets.VITE_EMAIL_JS_SERVICE_ID }}" >> .env
          echo "VITE_EMAIL_JS_TEMPLATE_ID=${{ secrets.VITE_EMAIL_JS_TEMPLATE_ID }}" >> .env

      - name: Build the Vite app
        run: npm run build

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: npm run deploy
